version: '3.8'

services:
  nginx:
    build: ./nginx
    image: registry.hosted-domains.com/shane/smwc-web-nginx:${VERSION}
    deploy:
      mode: global
    volumes:
      - data_dir:/data
    secrets:
      - source: cssnr.com.crt
        target: /etc/ssl/cssnr.com.crt
      - source: cssnr.com.key
        target: /etc/ssl/cssnr.com.key
      - source: cssnr_basic_http_auth
        target: /etc/nginx/auth.users
    ports:
      - "${DOCKER_PORT}:443"
    depends_on:
      - app

  app:
    build: ./app
    image: registry.hosted-domains.com/shane/smwc-web-app:${VERSION}
    env_file: ${ENV_FILE}
    command: "gunicorn smwc_web.wsgi:application -w 2 -b 0.0.0.0:9000"
    deploy:
      mode: global
    volumes:
      - data_dir:/data
    depends_on:
      - redis

  worker:
    image: registry.hosted-domains.com/shane/smwc-web-app:${VERSION}
    env_file: ${ENV_FILE}
    command: "celery -A smwc_web worker -l INFO -c 2"
    deploy:
      replicas: 1
    volumes:
      - data_dir:/data
    depends_on:
      - app

  beat:
    image: registry.hosted-domains.com/shane/smwc-web-app:${VERSION}
    env_file: ${ENV_FILE}
    command: "celery -A smwc_web beat -l INFO -S django_celery_beat.schedulers:DatabaseScheduler"
    deploy:
      replicas: 1
    depends_on:
      - app

  flower:
    image: mher/flower:0.9.5
    env_file: ${ENV_FILE}
    deploy:
      replicas: 1
    volumes:
      - flower_data:/data
    depends_on:
      - app

  redis:
    image: redis:6-alpine
    command: "redis-server --appendonly yes"
    deploy:
      replicas: 1
    volumes:
      - redis_data:/data

  memcached:
    image: memcached:alpine
    command: "memcached -I 4M"
    deploy:
      replicas: 1

secrets:
  cssnr.com.crt:
    external: true
  cssnr.com.key:
    external: true
  cssnr_basic_http_auth:
    external: true

volumes:
  data_dir:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${NFS_HOST},rw"
      device: ":${NFS_DIRECTORY}"
  flower_data:
  redis_data:
